# https://codesource.io/ci-cd-with-github-travis-ci-and-heroku/
sudo: required
language: node_js
node_js:
  - 14.16.0
services:
  - docker

before_script:
  - echo "Nothing to Run Before Script"

script:
  - echo "No tests to Run"

after_success:
  # Install AWS CLI
  # http://haoliangyu.github.io/blog/2018/03/19/AWS-ECS-auto-deployment-with-Travis-CI/
  - echo "Preparing for push to AWS ECR"
  - pip install --user awscli
  # aws ecr get-login depends on environment variables: AWS_ACCOUNT_ID, AWS_ACCESS_KEY_ID, and AWS_SECRET_ACCESS_KEY
  # to authenticate against the aws server.  These values should be provided in the travis environment variables.
  - aws ecr get-login --no-include-email
  # Build the docker image
  - docker image build -t ${IMGNAME}:${IMGVERSION} .
  # Tag the docker image with the repository address appended
  - docker tag ${IMGNAME}:${IMGVERSION} ${AWS_REPO_ADDRESS}/${IMGNAME}:${IMGVERSION}
  # Push to AWS ECR
  - docker push ${AWS_REPO_ADDRESS}/${IMGNAME}:${IMGVERSION} 


# Deploy to Heroku
deploy:
  provider: heroku
  api_key:
    main: ${HEROKU_API_KEY}
  app: opusmarket-be-docker
  on:
    branch: main